# Generated by Django 3.0.6 on 2020-05-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_exercises.Instructor'),
            preserve_default=False,
        ),
    ]
