# Generated by Django 3.0.6 on 2020-05-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_exercises', '0002_studentexercise_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='student_exercises.Cohort'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.CharField(max_length=50),
        ),
    ]
