# Generated by Django 3.0.6 on 2020-05-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_exercises', '0003_auto_20200507_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_exercises.Cohort'),
        ),
    ]
