# Generated by Django 3.0.6 on 2020-05-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_exercises', '0004_auto_20200507_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='_first_name',
        ),
    ]
