# Generated by Django 3.0.6 on 2020-05-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_exercises', '0005_auto_20200507_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cohort',
            new_name='_cohort',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='_first_name',
            new_name='first_name',
        ),
    ]
