# Generated by Django 3.0.6 on 2020-05-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_exercises', '0006_auto_20200507_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_cohort',
            new_name='cohort',
        ),
    ]
